import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/addons/loaders/DRACOLoader.js";
import { MeshoptDecoder } from "three/addons/libs/meshopt_decoder.module.js";
import {
  MODEL_SIZE_LIMIT,
  MODEL_LIBRARY_LIMIT,
  findModelResource,
  isModelDataURI,
  parseModelDocument,
  unpackGLB,
  type ImportedModel,
  type ModelSurface,
} from "./imported-model.ts";

import { disposeObjects } from "./model-resources.ts";
export { disposeObjects } from "./model-resources.ts";

export interface SurfaceSlot {
  info: ModelSurface;
  mesh: THREE.Mesh;
  index: number;
  original: THREE.Material;
}
export interface CustomRuntime {
  group: THREE.Group;
  slots: SurfaceSlot[];
  resources: THREE.Object3D[];
}

function uvAspect(mesh: THREE.Mesh, materialIndex: number) {
  const g = mesh.geometry,
    uv = g.getAttribute("uv"),
    pos = g.getAttribute("position");
  if (!uv || !pos) return 1;
  const group = g.groups.find((s) => s.materialIndex === materialIndex);
  const start = group?.start || 0,
    end = Math.min(start + (group?.count || 300), g.index?.count || pos.count);
  for (let i = start; i + 2 < end; i += 3) {
    const ids = [0, 1, 2].map((n) => (g.index ? g.index.getX(i + n) : i + n));
    const p = ids.map((id) =>
      new THREE.Vector3()
        .fromBufferAttribute(pos, id)
        .applyMatrix4(mesh.matrixWorld),
    );
    const u = ids.map((id) => new THREE.Vector2(uv.getX(id), uv.getY(id)));
    const a = p[1].sub(p[0]),
      b = p[2].sub(p[0]),
      c = u[1].sub(u[0]),
      d = u[2].sub(u[0]);
    const determinant = c.x * d.y - c.y * d.x;
    if (Math.abs(determinant) < 1e-8) continue;
    const du = a.clone().multiplyScalar(d.y).addScaledVector(b, -c.y);
    const dv = b.clone().multiplyScalar(c.x).addScaledVector(a, -d.x);
    const ratio = du.length() / dv.length();
    if (Number.isFinite(ratio) && ratio > 0)
      return Math.max(0.05, Math.min(20, ratio));
  }
  return 1;
}

export async function loadCustomModel(
  asset: Pick<ImportedModel, "document">,
): Promise<CustomRuntime> {
  const json = parseModelDocument(asset.document);
  const manager = new THREE.LoadingManager();
  let resourceFailed = false;
  manager.onError = () => {
    resourceFailed = true;
  };
  manager.setURLModifier((url) => {
    // Blob URLs are generated by GLTFLoader for embedded buffer-view images.
    if (isModelDataURI(url) || url.startsWith("blob:")) return url;
    throw new Error("The model contains an unsupported external resource.");
  });
  // Draco's decoder is bundled locally and uses a separate loading manager.
  const draco = new DRACOLoader().setDecoderPath("/decoders/draco/");
  const loader = new GLTFLoader(manager)
    .setDRACOLoader(draco)
    .setMeshoptDecoder(MeshoptDecoder);
  let resources: THREE.Object3D[] = [];
  try {
    const gltf = await loader.parseAsync(JSON.stringify(json), "");
    resources = gltf.scenes;
    if (resourceFailed)
      throw new Error(
        "A model texture could not be decoded. Use PNG, JPEG, or WebP textures.",
      );
    const root = gltf.scene;
    const remove: THREE.Object3D[] = [];
    root.traverse((o) => {
      if (o instanceof THREE.Light || o instanceof THREE.Camera) remove.push(o);
    });
    remove.forEach((o) => o.removeFromParent());
    root.updateMatrixWorld(true);
    const box = new THREE.Box3().setFromObject(root, true),
      size = box.getSize(new THREE.Vector3());
    const extent = Math.max(size.x, size.y, size.z);
    if (!Number.isFinite(extent) || extent <= 0)
      throw new Error("The model has no visible mesh geometry.");
    const slots: SurfaceSlot[] = [];
    let vertices = 0,
      meshIndex = 0;
    root.traverse((o) => {
      if (!(o instanceof THREE.Mesh)) return;
      const position = o.geometry.getAttribute("position");
      vertices += position?.count || 0;
      if (vertices > 5000000)
        throw new Error(
          "This model is too complex. Export a version with fewer than 5 million vertices.",
        );
      if (position)
        for (let i = 0; i < position.count; i++) {
          if (
            ![position.getX(i), position.getY(i), position.getZ(i)].every(
              Number.isFinite,
            )
          )
            throw new Error("The model contains invalid geometry.");
        }
      const materials = Array.isArray(o.material) ? o.material : [o.material];
      materials.forEach((material, index) =>
        slots.push({
          mesh: o,
          index,
          original: material,
          info: {
            id: `${meshIndex}:${index}`,
            name: `${o.name || `Mesh ${meshIndex + 1}`}${material.name ? ` · ${material.name}` : ""}`.slice(
              0,
              200,
            ),
            hasUV: !!o.geometry.getAttribute("uv"),
            aspect: uvAspect(o, index),
          },
        }),
      );
      meshIndex++;
    });
    if (!slots.length || slots.length > 2000)
      throw new Error("Use a model with 1–2,000 mesh surfaces.");
    const normalization = new THREE.Group();
    normalization.scale.setScalar(4 / extent);
    normalization.position
      .copy(box.getCenter(new THREE.Vector3()))
      .multiplyScalar(-4 / extent);
    normalization.add(root);
    const group = new THREE.Group();
    group.add(normalization);
    return { group, slots, resources };
  } catch (error) {
    disposeObjects(resources);
    throw error;
  } finally {
    draco.dispose();
  }
}

export function setSurfaceMaterial(
  slot: SurfaceSlot,
  material: THREE.Material,
) {
  if (Array.isArray(slot.mesh.material)) {
    const materials = [...slot.mesh.material];
    materials[slot.index] = material;
    slot.mesh.material = materials;
  } else slot.mesh.material = material;
}

async function dataURI(blob: Blob, mime = "application/octet-stream") {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      resolve(`data:${mime};base64,${String(reader.result).split(",")[1]}`);
    reader.onerror = () =>
      reject(new Error("Could not read the selected file."));
    reader.readAsDataURL(blob);
  });
}

async function embedGLTF(entry: File, files: File[]) {
  const isGLB = /\.glb$/i.test(entry.name);
  const { document, binary } = isGLB
    ? unpackGLB(await entry.arrayBuffer())
    : { document: await entry.text(), binary: undefined };
  const json = JSON.parse(document);
  if (binary) {
    if (!json.buffers?.[0] || json.buffers[0].uri)
      throw new Error("The GLB buffer is invalid.");
    json.buffers[0].uri = await dataURI(new Blob([new Uint8Array(binary)]));
  }
  const path = (f: File) => f.webkitRelativePath || f.name;
  const paths = files.map(path);
  const visit = async (value: unknown): Promise<void> => {
    if (!value || typeof value !== "object") return;
    for (const [key, child] of Object.entries(value)) {
      if (
        key === "uri" &&
        typeof child === "string" &&
        !isModelDataURI(child)
      ) {
        const resourcePath = findModelResource(child, path(entry), paths);
        const file = files[paths.indexOf(resourcePath)];
        const extension = file.name.split(".").pop()?.toLowerCase();
        const mime =
          extension === "png"
            ? "image/png"
            : ["jpg", "jpeg"].includes(extension || "")
              ? "image/jpeg"
              : extension === "webp"
                ? "image/webp"
                : "application/octet-stream";
        (value as Record<string, unknown>)[key] = await dataURI(file, mime);
      } else await visit(child);
    }
  };
  await visit(json);
  return JSON.stringify(json);
}

export async function importModelFiles(files: File[]): Promise<ImportedModel> {
  const entries = files.filter((f) => /\.(glb|gltf|usdz)$/i.test(f.name));
  if (entries.length !== 1)
    throw new Error(
      "Select one GLB, glTF, or USDZ model, together with any textures and .bin files it uses.",
    );
  const bytes = files.reduce((n, f) => n + f.size, 0);
  if (files.length > 200 || bytes > MODEL_SIZE_LIMIT)
    throw new Error(
      "Select up to 200 files, with a combined size of 64 MB or less.",
    );
  const entry = entries[0],
    isUSDZ = /\.usdz$/i.test(entry.name);
  const embedded = isUSDZ
    ? await (
        await import("./usdz-model.ts")
      ).convertUSDZ(await entry.arrayBuffer())
    : await embedGLTF(entry, files);
  if (embedded.length > MODEL_LIBRARY_LIMIT)
    throw new Error(
      "The converted model exceeds the 96 MB library limit. Use a smaller model or lower-resolution textures.",
    );
  const runtime = await loadCustomModel({ document: embedded });
  try {
    return {
      id: crypto.randomUUID(),
      name: entry.name.replace(/\.(glb|gltf|usdz)$/i, "").slice(0, 100),
      format: isUSDZ ? "USDZ" : /\.glb$/i.test(entry.name) ? "GLB" : "glTF",
      document: embedded,
      bytes,
      surfaces: runtime.slots.map((s) => s.info),
    };
  } finally {
    disposeObjects(runtime.resources);
  }
}
